<?php
/**
 * StorageApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * mcode-sdk-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * StorageApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StorageApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'deleteByKeyFromStorage' => [
            'application/json',
        ],
        'getByKeyFromStorage' => [
            'application/json',
        ],
        'incrementCounter' => [
            'application/json',
        ],
        'upsertByKeyFromStorage' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation deleteByKeyFromStorage
     *
     * @param  string $key key (required)
     * @param  string $x_monday_access_token x_monday_access_token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteByKeyFromStorage($key, $x_monday_access_token, string $contentType = self::contentTypes['deleteByKeyFromStorage'][0])
    {
        $this->deleteByKeyFromStorageWithHttpInfo($key, $x_monday_access_token, $contentType);
    }

    /**
     * Operation deleteByKeyFromStorageWithHttpInfo
     *
     * @param  string $key (required)
     * @param  string $x_monday_access_token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteByKeyFromStorageWithHttpInfo($key, $x_monday_access_token, string $contentType = self::contentTypes['deleteByKeyFromStorage'][0])
    {
        $request = $this->deleteByKeyFromStorageRequest($key, $x_monday_access_token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation deleteByKeyFromStorageAsync
     *
     * @param  string $key (required)
     * @param  string $x_monday_access_token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteByKeyFromStorageAsync($key, $x_monday_access_token, string $contentType = self::contentTypes['deleteByKeyFromStorage'][0])
    {
        return $this->deleteByKeyFromStorageAsyncWithHttpInfo($key, $x_monday_access_token, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteByKeyFromStorageAsyncWithHttpInfo
     *
     * @param  string $key (required)
     * @param  string $x_monday_access_token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteByKeyFromStorageAsyncWithHttpInfo($key, $x_monday_access_token, string $contentType = self::contentTypes['deleteByKeyFromStorage'][0])
    {
        $returnType = '';
        $request = $this->deleteByKeyFromStorageRequest($key, $x_monday_access_token, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteByKeyFromStorage'
     *
     * @param  string $key (required)
     * @param  string $x_monday_access_token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteByKeyFromStorageRequest($key, $x_monday_access_token, string $contentType = self::contentTypes['deleteByKeyFromStorage'][0])
    {

        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $key when calling deleteByKeyFromStorage'
            );
        }

        // verify the required parameter 'x_monday_access_token' is set
        if ($x_monday_access_token === null || (is_array($x_monday_access_token) && count($x_monday_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_monday_access_token when calling deleteByKeyFromStorage'
            );
        }


        $resourcePath = '/storage/{key}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_monday_access_token !== null) {
            $headerParams['x-monday-access-token'] = ObjectSerializer::toHeaderValue($x_monday_access_token);
        }

        // path params
        if ($key !== null) {
            $resourcePath = str_replace(
                '{' . 'key' . '}',
                ObjectSerializer::toPathValue($key),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getByKeyFromStorage
     *
     * @param  string $key key (required)
     * @param  bool $shared shared (required)
     * @param  string $x_monday_access_token x_monday_access_token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\StorageDataContract|\OpenAPI\Client\Model\GetByKeyFromStorage404Response|\OpenAPI\Client\Model\GetByKeyFromStorage500Response
     */
    public function getByKeyFromStorage($key, $shared, $x_monday_access_token, string $contentType = self::contentTypes['getByKeyFromStorage'][0])
    {
        list($response) = $this->getByKeyFromStorageWithHttpInfo($key, $shared, $x_monday_access_token, $contentType);
        return $response;
    }

    /**
     * Operation getByKeyFromStorageWithHttpInfo
     *
     * @param  string $key (required)
     * @param  bool $shared (required)
     * @param  string $x_monday_access_token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\StorageDataContract|\OpenAPI\Client\Model\GetByKeyFromStorage404Response|\OpenAPI\Client\Model\GetByKeyFromStorage500Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getByKeyFromStorageWithHttpInfo($key, $shared, $x_monday_access_token, string $contentType = self::contentTypes['getByKeyFromStorage'][0])
    {
        $request = $this->getByKeyFromStorageRequest($key, $shared, $x_monday_access_token, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\StorageDataContract' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\StorageDataContract' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\StorageDataContract', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\OpenAPI\Client\Model\GetByKeyFromStorage404Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\GetByKeyFromStorage404Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\GetByKeyFromStorage404Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\OpenAPI\Client\Model\GetByKeyFromStorage500Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\GetByKeyFromStorage500Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\GetByKeyFromStorage500Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\StorageDataContract';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\StorageDataContract',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetByKeyFromStorage404Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetByKeyFromStorage500Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getByKeyFromStorageAsync
     *
     * @param  string $key (required)
     * @param  bool $shared (required)
     * @param  string $x_monday_access_token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getByKeyFromStorageAsync($key, $shared, $x_monday_access_token, string $contentType = self::contentTypes['getByKeyFromStorage'][0])
    {
        return $this->getByKeyFromStorageAsyncWithHttpInfo($key, $shared, $x_monday_access_token, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getByKeyFromStorageAsyncWithHttpInfo
     *
     * @param  string $key (required)
     * @param  bool $shared (required)
     * @param  string $x_monday_access_token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getByKeyFromStorageAsyncWithHttpInfo($key, $shared, $x_monday_access_token, string $contentType = self::contentTypes['getByKeyFromStorage'][0])
    {
        $returnType = '\OpenAPI\Client\Model\StorageDataContract';
        $request = $this->getByKeyFromStorageRequest($key, $shared, $x_monday_access_token, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getByKeyFromStorage'
     *
     * @param  string $key (required)
     * @param  bool $shared (required)
     * @param  string $x_monday_access_token (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getByKeyFromStorageRequest($key, $shared, $x_monday_access_token, string $contentType = self::contentTypes['getByKeyFromStorage'][0])
    {

        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $key when calling getByKeyFromStorage'
            );
        }

        // verify the required parameter 'shared' is set
        if ($shared === null || (is_array($shared) && count($shared) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $shared when calling getByKeyFromStorage'
            );
        }

        // verify the required parameter 'x_monday_access_token' is set
        if ($x_monday_access_token === null || (is_array($x_monday_access_token) && count($x_monday_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_monday_access_token when calling getByKeyFromStorage'
            );
        }


        $resourcePath = '/storage/{key}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $shared,
            'shared', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);

        // header params
        if ($x_monday_access_token !== null) {
            $headerParams['x-monday-access-token'] = ObjectSerializer::toHeaderValue($x_monday_access_token);
        }

        // path params
        if ($key !== null) {
            $resourcePath = str_replace(
                '{' . 'key' . '}',
                ObjectSerializer::toPathValue($key),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation incrementCounter
     *
     * @param  string $x_monday_access_token x_monday_access_token (required)
     * @param  \OpenAPI\Client\Model\IncrementCounterParams $increment_counter_params increment_counter_params (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incrementCounter'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\IncrementCounter200Response
     */
    public function incrementCounter($x_monday_access_token, $increment_counter_params, string $contentType = self::contentTypes['incrementCounter'][0])
    {
        list($response) = $this->incrementCounterWithHttpInfo($x_monday_access_token, $increment_counter_params, $contentType);
        return $response;
    }

    /**
     * Operation incrementCounterWithHttpInfo
     *
     * @param  string $x_monday_access_token (required)
     * @param  \OpenAPI\Client\Model\IncrementCounterParams $increment_counter_params (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incrementCounter'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\IncrementCounter200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function incrementCounterWithHttpInfo($x_monday_access_token, $increment_counter_params, string $contentType = self::contentTypes['incrementCounter'][0])
    {
        $request = $this->incrementCounterRequest($x_monday_access_token, $increment_counter_params, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\IncrementCounter200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\IncrementCounter200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\IncrementCounter200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\IncrementCounter200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\IncrementCounter200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation incrementCounterAsync
     *
     * @param  string $x_monday_access_token (required)
     * @param  \OpenAPI\Client\Model\IncrementCounterParams $increment_counter_params (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incrementCounter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function incrementCounterAsync($x_monday_access_token, $increment_counter_params, string $contentType = self::contentTypes['incrementCounter'][0])
    {
        return $this->incrementCounterAsyncWithHttpInfo($x_monday_access_token, $increment_counter_params, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation incrementCounterAsyncWithHttpInfo
     *
     * @param  string $x_monday_access_token (required)
     * @param  \OpenAPI\Client\Model\IncrementCounterParams $increment_counter_params (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incrementCounter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function incrementCounterAsyncWithHttpInfo($x_monday_access_token, $increment_counter_params, string $contentType = self::contentTypes['incrementCounter'][0])
    {
        $returnType = '\OpenAPI\Client\Model\IncrementCounter200Response';
        $request = $this->incrementCounterRequest($x_monday_access_token, $increment_counter_params, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'incrementCounter'
     *
     * @param  string $x_monday_access_token (required)
     * @param  \OpenAPI\Client\Model\IncrementCounterParams $increment_counter_params (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['incrementCounter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function incrementCounterRequest($x_monday_access_token, $increment_counter_params, string $contentType = self::contentTypes['incrementCounter'][0])
    {

        // verify the required parameter 'x_monday_access_token' is set
        if ($x_monday_access_token === null || (is_array($x_monday_access_token) && count($x_monday_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_monday_access_token when calling incrementCounter'
            );
        }

        // verify the required parameter 'increment_counter_params' is set
        if ($increment_counter_params === null || (is_array($increment_counter_params) && count($increment_counter_params) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $increment_counter_params when calling incrementCounter'
            );
        }


        $resourcePath = '/storage/counter/increment';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_monday_access_token !== null) {
            $headerParams['x-monday-access-token'] = ObjectSerializer::toHeaderValue($x_monday_access_token);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($increment_counter_params)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($increment_counter_params));
            } else {
                $httpBody = $increment_counter_params;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation upsertByKeyFromStorage
     *
     * @param  string $key key (required)
     * @param  string $x_monday_access_token x_monday_access_token (required)
     * @param  \OpenAPI\Client\Model\JsonDataContract $json_data_contract json_data_contract (required)
     * @param  bool $shared shared (optional)
     * @param  string $previous_version previous_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['upsertByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\UpsertByKeyFromStorage200Response
     */
    public function upsertByKeyFromStorage($key, $x_monday_access_token, $json_data_contract, $shared = null, $previous_version = null, string $contentType = self::contentTypes['upsertByKeyFromStorage'][0])
    {
        list($response) = $this->upsertByKeyFromStorageWithHttpInfo($key, $x_monday_access_token, $json_data_contract, $shared, $previous_version, $contentType);
        return $response;
    }

    /**
     * Operation upsertByKeyFromStorageWithHttpInfo
     *
     * @param  string $key (required)
     * @param  string $x_monday_access_token (required)
     * @param  \OpenAPI\Client\Model\JsonDataContract $json_data_contract (required)
     * @param  bool $shared (optional)
     * @param  string $previous_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['upsertByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\UpsertByKeyFromStorage200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function upsertByKeyFromStorageWithHttpInfo($key, $x_monday_access_token, $json_data_contract, $shared = null, $previous_version = null, string $contentType = self::contentTypes['upsertByKeyFromStorage'][0])
    {
        $request = $this->upsertByKeyFromStorageRequest($key, $x_monday_access_token, $json_data_contract, $shared, $previous_version, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\UpsertByKeyFromStorage200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\UpsertByKeyFromStorage200Response' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\UpsertByKeyFromStorage200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\UpsertByKeyFromStorage200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\UpsertByKeyFromStorage200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation upsertByKeyFromStorageAsync
     *
     * @param  string $key (required)
     * @param  string $x_monday_access_token (required)
     * @param  \OpenAPI\Client\Model\JsonDataContract $json_data_contract (required)
     * @param  bool $shared (optional)
     * @param  string $previous_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['upsertByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function upsertByKeyFromStorageAsync($key, $x_monday_access_token, $json_data_contract, $shared = null, $previous_version = null, string $contentType = self::contentTypes['upsertByKeyFromStorage'][0])
    {
        return $this->upsertByKeyFromStorageAsyncWithHttpInfo($key, $x_monday_access_token, $json_data_contract, $shared, $previous_version, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation upsertByKeyFromStorageAsyncWithHttpInfo
     *
     * @param  string $key (required)
     * @param  string $x_monday_access_token (required)
     * @param  \OpenAPI\Client\Model\JsonDataContract $json_data_contract (required)
     * @param  bool $shared (optional)
     * @param  string $previous_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['upsertByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function upsertByKeyFromStorageAsyncWithHttpInfo($key, $x_monday_access_token, $json_data_contract, $shared = null, $previous_version = null, string $contentType = self::contentTypes['upsertByKeyFromStorage'][0])
    {
        $returnType = '\OpenAPI\Client\Model\UpsertByKeyFromStorage200Response';
        $request = $this->upsertByKeyFromStorageRequest($key, $x_monday_access_token, $json_data_contract, $shared, $previous_version, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'upsertByKeyFromStorage'
     *
     * @param  string $key (required)
     * @param  string $x_monday_access_token (required)
     * @param  \OpenAPI\Client\Model\JsonDataContract $json_data_contract (required)
     * @param  bool $shared (optional)
     * @param  string $previous_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['upsertByKeyFromStorage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function upsertByKeyFromStorageRequest($key, $x_monday_access_token, $json_data_contract, $shared = null, $previous_version = null, string $contentType = self::contentTypes['upsertByKeyFromStorage'][0])
    {

        // verify the required parameter 'key' is set
        if ($key === null || (is_array($key) && count($key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $key when calling upsertByKeyFromStorage'
            );
        }

        // verify the required parameter 'x_monday_access_token' is set
        if ($x_monday_access_token === null || (is_array($x_monday_access_token) && count($x_monday_access_token) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_monday_access_token when calling upsertByKeyFromStorage'
            );
        }

        // verify the required parameter 'json_data_contract' is set
        if ($json_data_contract === null || (is_array($json_data_contract) && count($json_data_contract) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $json_data_contract when calling upsertByKeyFromStorage'
            );
        }




        $resourcePath = '/storage/{key}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $shared,
            'shared', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $previous_version,
            'previousVersion', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_monday_access_token !== null) {
            $headerParams['x-monday-access-token'] = ObjectSerializer::toHeaderValue($x_monday_access_token);
        }

        // path params
        if ($key !== null) {
            $resourcePath = str_replace(
                '{' . 'key' . '}',
                ObjectSerializer::toPathValue($key),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($json_data_contract)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($json_data_contract));
            } else {
                $httpBody = $json_data_contract;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
